# Builds ddaccess.dll (the mod) using MSVC.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "vswhere not found: $vswhere" }
$vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $vs) { throw "MSVC C++ tools not found. Is the VCTools workload installed?" }
$vcvars = Join-Path $vs "VC\Auxiliary\Build\vcvars64.bat"
if (-not (Test-Path $vcvars)) { throw "vcvars64.bat not found: $vcvars" }

New-Item -ItemType Directory -Force "$root\build" | Out-Null

# ---- Embed the translations ----
$langDir = Join-Path $root "lang"
$incPath = Join-Path $root "src\core\axlang_embedded.inc"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// GENERATED by Mod\build.ps1 from Mod\lang\*.txt -- do not edit, not committed.")
$langNames = @()
if (Test-Path $langDir) {
    foreach ($f in (Get-ChildItem $langDir -Filter *.txt | Where-Object { $_.Name -ne "README.txt" -and $_.Name -ne "english.txt" } | Sort-Object Name)) {
        $bytes = [IO.File]::ReadAllBytes($f.FullName)
        if ($bytes.Length -eq 0) { continue }
        $name = $f.BaseName.ToLowerInvariant()
        $id = $name -replace "[^a-z0-9]", "_"
        $langNames += ,@($name, $id)
        [void]$sb.Append("static const unsigned char kAxLangBytes_$id[] = {")
        for ($i = 0; $i -lt $bytes.Length; $i++) {
            if ($i % 24 -eq 0) { [void]$sb.Append("`n") }
            [void]$sb.Append($bytes[$i])
            [void]$sb.Append(",")
        }
        [void]$sb.AppendLine("`n};")
    }
}
[void]$sb.AppendLine("static const AxEmbeddedLang kAxEmbeddedLangs[] = {")
foreach ($n in $langNames) {
    [void]$sb.AppendLine("    { `"$($n[0])`", kAxLangBytes_$($n[1]), (int)sizeof(kAxLangBytes_$($n[1])) },")
}
[void]$sb.AppendLine("    { 0, 0, 0 }  // sentinel: keeps the array non-empty with zero languages")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const int kAxEmbeddedLangCount = $($langNames.Count);")
[IO.File]::WriteAllText($incPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "[+] Embedded $($langNames.Count) translation(s) -> src\core\axlang_embedded.inc" -ForegroundColor Green

$bat = @"
@echo off
call "$vcvars" >nul 2>nul
cd /d "$root\build"
cl /nologo /LD /O2 /MT /EHsc /std:c++17 /D_CRT_SECURE_NO_WARNINGS /I "$root\lib\prism" /I "$root\src" /Fe:ddaccess.dll "$root\src\dllmain.cpp" "$root\src\core\speech.cpp" "$root\src\core\gameread.cpp" "$root\src\core\subtitles.cpp" "$root\src\core\hooks.cpp" "$root\src\game\gamebuild.cpp" "$root\src\core\axstrings.cpp" "$root\src\frontend\loading.cpp" "$root\src\frontend\sharedui.cpp" "$root\src\frontend\options.cpp" "$root\src\frontend\dialog.cpp" "$root\src\frontend\display.cpp" "$root\src\frontend\tutorial.cpp" "$root\src\frontend\naming.cpp" "$root\src\frontend\pause.cpp" "$root\src\input\synth.cpp" "$root\src\input\layout.cpp" "$root\src\town\estate.cpp" "$root\src\town\map.cpp" "$root\src\town\districts.cpp" "$root\src\town\embark.cpp" "$root\src\town\provision.cpp" "$root\src\town\buildings.cpp" "$root\src\town\party.cpp" "$root\src\town\trinkets.cpp" "$root\src\town\exchange.cpp" "$root\src\town\barks.cpp" "$root\src\town\events.cpp" "$root\src\raid\resting.cpp" "$root\src\raid\raidmap.cpp" "$root\src\raid\dungeonview.cpp" "$root\src\raid\actionbar.cpp" "$root\src\raid\camp.cpp" "$root\src\raid\loot.cpp" "$root\src\raid\eventscroll.cpp" "$root\src\raid\inventory.cpp" "$root\src\raid\light.cpp" "$root\src\raid\combattext.cpp" "$root\src\raid\results.cpp" "$root\src\raid\quest.cpp" "$root\src\sheet\charsheet.cpp" "$root\src\sheet\composers.cpp" "$root\src\settings\keymap.cpp" "$root\src\settings\modmenu.cpp" "$root\src\dlc\color_of_madness\wave.cpp" "$root\src\dlc\butchers_circus\dueling.cpp" "$root\src\dlc\butchers_circus\ring.cpp" "$root\src\dlc\butchers_circus\pit.cpp" "$root\src\dlc\butchers_circus\matchresults.cpp" "$root\src\dlc\butchers_circus\prizebox.cpp" "$root\src\dlc\butchers_circus\rankings.cpp" "$root\src\dlc\butchers_circus\banner.cpp" /link "$root\lib\prism\prism.lib" user32.lib
if errorlevel 1 exit /b 1
"@
$batPath = Join-Path $env:TEMP "dd_mod_build.bat"
Set-Content -Path $batPath -Value $bat -Encoding ascii
cmd /c "`"$batPath`""
if ($LASTEXITCODE -ne 0) { throw "Build failed (exit $LASTEXITCODE)" }
Write-Host "`n[+] Build OK. Outputs in $root\build" -ForegroundColor Green
Get-ChildItem "$root\build" -Include ddaccess.dll -Recurse | Select-Object Name,Length

# ---- Deploy ----
$gameDir = "C:\Program Files (x86)\Steam\steamapps\common\DarkestDungeon\_windows\win64"
$target  = Join-Path $gameDir "ddaccess.dll"

if (-not (Test-Path $gameDir)) {
    Write-Host "[!] Game directory not found, NOT deployed: $gameDir" -ForegroundColor Yellow
    Write-Host "    The game will keep loading whatever ddaccess.dll it already has." -ForegroundColor Yellow
    return
}
if (Get-Process -Name "Darkest*" -ErrorAction SilentlyContinue) {
    Write-Host "[!] Darkest Dungeon is RUNNING -- NOT deployed." -ForegroundColor Yellow
    Write-Host "    Close the game, re-run this script, then start + inject again." -ForegroundColor Yellow
    return
}
try {
    Copy-Item "$root\build\ddaccess.dll" $target -Force -ErrorAction Stop
    Write-Host "[+] Deployed -> $target" -ForegroundColor Green
} catch {
    Write-Host "[!] Deploy FAILED: $_" -ForegroundColor Red
    Write-Host "    The build is fine; the game dir copy is stale. Copy it by hand before testing." -ForegroundColor Red
}

$prismSrc = "$root\lib\prism\prism.dll"
$prismDst = Join-Path $gameDir "prism.dll"
if (-not (Test-Path $prismDst) -or
    ((Get-Item $prismSrc).Length -ne (Get-Item $prismDst).Length)) {
    try {
        Copy-Item $prismSrc $prismDst -Force -ErrorAction Stop
        Write-Host "[+] Deployed -> $prismDst" -ForegroundColor Green
    } catch {
        Write-Host "[!] prism.dll deploy FAILED: $_ -- the mod DLL cannot load without it." -ForegroundColor Red
    }
}

$langDst = Join-Path $gameDir "ddaccess-lang"
if (Test-Path $langDst) {
    Remove-Item $langDst -Recurse -Force
    Write-Host "[+] Removed the retired ddaccess-lang folder from the game dir" -ForegroundColor Green
}
